### ISSUE TITLE
Should return 400 instead of 500 on AWS call error?

### ISSUE THREAD

**Issue by mechpen** [jtblin/kube2iam#154]
Returning 500 status code is misleading at here:

https://github.com/jtblin/kube2iam/blob/0.10.0/server/server.go#L242

When a pod requests a IAM role that it has no permission, it should get a 400 instead of 500.

**Comment by jtblin** [comment]
```
        credentials, err := s.iam.AssumeRole(wantedRoleARN, remoteIP)
	if err != nil {
		roleLogger.Errorf("Error assuming role %+v", err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
```

We don't know if a pod requests an IAM role that it has no permission for this error, it could be a network issue, a configuration issue at the node level, etc., hence why we return a 500 here.

When a pod pod requests an IAM role that it has no permission, we do return a 403 as per the test before.

```
    if wantedRoleARN != roleMapping.Role {
		roleLogger.WithField("params.iam.role", wantedRole).
			Error("Invalid role: does not match annotated role")
		http.Error(w, fmt.Sprintf("Invalid role %s", wantedRole), http.StatusForbidden)
		return
	}
```

**Comment by mechpen** [comment]
> When a pod pod requests an IAM role that it has no permission, we do return a 403 as per the test before.

The code does not check if the IAM role exists in AWS or if the trust relationship is setup properly.

To me, 500 status codes are server internal bugs, which should give server backtrace and get fixed.  The user mis-configuration, or external errors should gives 400.

**Comment by jtblin** [comment]
> The user mis-configuration, or external errors should give 400.

That's factually incorrect. 400 errors are reserved for http requests where the syntax is invalid. In this case, the http request is valid, but we aren't sure why our request to sts fails so returning a 500 so that the owner investigates the root cause is the right thing to do imho. 

Reference https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

> The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server could not understand the request due to invalid syntax.

We could try to introspect the error returned by AWS but I am unsure if this is actually possible. We do not check that the role exists because that would slow down returning the credentials even more. We do check if there is a role set for the pod and returns a 404 if we cannot find a mapping though.
