### ISSUE TITLE
Portworx DaemonSet not assuming the annotation role

### ISSUE THREAD

**Issue by cdenneen** [jtblin/kube2iam#176]
So I've annotated this role on a aws-cli container and it works just fine. The get-caller-identity returns the role arn properly but when the same role is applied to the DaemonSet for portworx it fails to assume that annotated role and falls back to the default "instancerole". 

How can I fix this?

{
    "DecodedMessage": "{\"allowed\":false,\"explicitDeny\":false,\"matchedStatements\":{\"items\":[]},\"failures\":{\"items\":[]},\"context\":{\"principal\":{\"id\":\"YYYYYYYYYYYYYYYYYY:i-ZZZZZZZZZZZZZZZZZZ\",\"arn\":\"arn:aws:sts::XXXXXXXXXXXXXXXXX:assumed-role/eks1dev-workers1-NodeInstanceRole-1VY13IIH9VLKW/i-ZZZZZZZZZZZZZZZZZZZZZZZ\"},\"action\":\"ec2:CreateVolume\",\"resource\":\"arn:aws:ec2:us-east-1:XXXXXXXXXXXXXX:volume/*\",\"conditions\":{\"items\":[{\"key\":\"aws:Resource\",\"values\":{\"items\":[{\"value\":\"volume/*\"}]}},{\"key\":\"aws:Account\",\"values\":{\"items\":[{\"value\":\"XXXXXXXXXXXXXx\"}]}},{\"key\":\"ec2:AvailabilityZone\",\"values\":{\"items\":[{\"value\":\"us-east-1b\"}]}},{\"key\":\"ec2:Encrypted\",\"values\":{\"items\":[{\"value\":\"false\"}]}},{\"key\":\"ec2:VolumeType\",\"values\":{\"items\":[{\"value\":\"gp2\"}]}},{\"key\":\"aws:Region\",\"values\":{\"items\":[{\"value\":\"us-east-1\"}]}},{\"key\":\"aws:Service\",\"values\":{\"items\":[{\"value\":\"ec2\"}]}},{\"key\":\"ec2:VolumeID\",\"values\":{\"items\":[{\"value\":\"*\"}]}},{\"key\":\"ec2:VolumeSize\",\"values\":{\"items\":[{\"value\":\"100\"}]}},{\"key\":\"aws:Type\",\"values\":{\"items\":[{\"value\":\"volume\"}]}},{\"key\":\"ec2:Region\",\"values\":{\"items\":[{\"value\":\"us-east-1\"}]}},{\"key\":\"aws:ARN\",\"values\":{\"items\":[{\"value\":\"arn:aws:ec2:us-east-1:XXXXXXXXXXXXXXX:volume/*\"}]}}]}}}"
}

**Comment by jrnt30** [comment]
I am unfamiliar with how PortWorx recommends deploying the DaemonSet but judging by what it's doing, it's also possible that it's being run as a privledged container and pulling a host IP instead of using the CNI.  

The Kube2IAM deployment only binds to the network interfaces that you specify in it's deployment and will not intercept calls for host networked containers.  

It sounds like you are actively running down some solutions and that it is in the "PortWorx" side of the house at this point.  

Going to close this but please feel free to reopen if it turns out this is a deficiency of the tool.
